added network selector
taubyte/tau pull request #8
Opened 2023-04-26 21:11 UTC by arontaubyte

Added a network selector to either connect to default, deprecated or custom network

Test: https://asciinema.org/a/7SR86HWO2a9scCjpEaCsR00v0

2023-04-26 23:03 UTC, tafseer-khan requested changes
Also would be nice instead of |grep FAIL 
|grep 'PASS:\|FAIL\|SKIP:'

That way it shows which tests passed, skip, or failed. Someone could put a lot of t.Skip() and a test that just sleeps to fake a recording

2023-04-27 03:54 UTC, skelouse requested changes
May be better to write it as it's own command, unless adding other resource esqu commands in the future `tau network` would fit.  Placing it in select gives the idea it can be created and destroyed as other resources.  

Also need to add env variables to the README

2023-04-27 03:54 UTC, skelouse commented on lib/domain/fqdn.go
> +
resp.Body.Close()

2023-04-27 03:54 UTC, skelouse commented on cli/commands/resources/network/types.go
> +	return nil
return common.NotImplemented

2023-04-27 03:54 UTC, skelouse commented on cli/commands/resources/network/types.go
> +	return nil
return common.NotImplemented

2023-04-27 03:54 UTC, skelouse commented on env/network.go
> +	if exist == true && len(network) > 0 {
Why check?  returning network, nil either way

2023-04-27 03:54 UTC, skelouse commented on env/network.go
> +	if exist == true && len(fqdn) > 0 {
same

2023-04-27 19:21 UTC, arontaubyte commented on singletons/auth_client/client.go
> +	case common.DefaultNetwork:
added as todo.

2023-06-06 18:32 UTC, tafseer-khan approved these changes

2023-06-07 16:21 UTC, merged